services:
  url-shortner-db:
    container_name: url-shortner-db
    image: postgres:16-alpine
    ports:
      - "${PSQL_EXTERNAL_PORT}:5432"
    networks:
      - internal
    environment:
      - POSTGRES_USER=${PSQL_USER}
      - POSTGRES_PASSWORD=${PSQL_PASSWORD}
      - POSTGRES_DB=${PSQL_DATABASE}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PSQL_USER} -d ${PSQL_DATABASE}"]
      interval: 5s
      timeout: 5s
      retries: 5

  url-shortener-redis:
    container_name: url-shortner-redis
    image: redis:7-alpine
    ports:
      - "${REDIS_EXTERNAL_PORT}:6379"
    networks:
      - internal
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    command: redis-server --requirepass ${REDIS_PASSWORD}

networks:
  internal:
    driver: bridge