create table clicks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    clicked_at TIMESTAMP(6) NOT NULL,
    country VARCHAR(255),
    ip_address VARCHAR(255),
    referrer VARCHAR(255),
    url_id BIGINT NOT NULL,

    PRIMARY KEY (id),
    CONSTRAINT fk_clicks_urls FOREIGN KEY (url_id) REFERENCES urls(id)
);